// <auto-generated />
using ef_core_poc.model;
using ef_core_poc.sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace efcorepocsql.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180224181032_AddScriptsRun_run_action")]
    partial class AddScriptsRun_run_action
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ef_core_poc.model.ScriptsRun", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("entered_by")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("entry_date");

                    b.Property<DateTime?>("modified_date");

                    b.Property<bool>("one_time_script");

                    b.Property<int>("run_action");

                    b.Property<string>("script_name")
                        .HasMaxLength(255);

                    b.Property<string>("text_hash")
                        .HasMaxLength(512);

                    b.Property<string>("text_of_script")
                        .HasColumnType("text");

                    b.Property<long>("version_id");

                    b.HasKey("id");

                    b.ToTable("scripts_run","RoundhousE");
                });
#pragma warning restore 612, 618
        }
    }
}
